version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging in to AWS ECR
      - docker --version
      - aws --version
      - REPOSITORY_URI=612881658900.dkr.ecr.us-east-1.amazonaws.com/egala/egala-server
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Builing docker image on `date` .......
      - docker build -t egala/egala-server .
      - docker tag egala/egala-server:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing image to repo
      - docker push $REPOSITORY_URI:latest